steps:
  - label: ":hammer_and_wrench: build + test"
    command: /usr/local/bin/sbt coverage test coverageReport
    plugins:
      docker#v1.1.1:
        debug: false
        image: bigtruedata/sbt
        workdir: /app
    artifact_paths:
      - target/scala-2.11/scoverage-report/scoverage.xml
      - target/scala-2.11/scoverage-data/scoverage.coverage.xml
      - target/scala-2.11/coverage-report/cobertura.xml
  - wait
  - label: ":mag: coverage report"
    command: |
      buildkite-agent artifact download "target/*" . && \
      bash <(curl -s https://codecov.io/bash) -t 5cec588e-3b45-4793-acda-74a5075b4c9d
