steps:
  - command: |
      sbt coverage test coverageReport
    artifact_paths: target/scala-*/scoverage-report/*.xml
    plugins:
      docker#v1.1.1:
        image: bigtruedata/sbt
        workdir: /app
  - wait
  - command: bash <(curl -s https://codecov.io/bash) -t 5cec588e-3b45-4793-acda-74a5075b4c9d
