steps:
  - command: sbt coverage test coverageReport
    artifact_paths:
      - target/scala-2.11/scoverage-report/scoverage.xml
      - target/scala-2.11/scoverage-data/scoverage.coverage.xml
      - target/scala-2.11/coverage-report/cobertura.xml
    plugins:
      docker#v1.1.1:
        image: bigtruedata/sbt
        workdir: /app
  - wait
  - command: bash <(curl -s https://codecov.io/bash) -t 5cec588e-3b45-4793-acda-74a5075b4c9d
