steps:
  - command: curl -Ls https://git.io/sbt > ~/bin/sbt && chmod 0755 ~/bin/sbt
  - command: |
      ~/bin/sbt coverage test coverageReport && \
      bash <(curl -s https://codecov.io/bash) -t 5cec588e-3b45-4793-acda-74a5075b4c9d
    artifact_paths: "target/**/*.jar"
